version: "2"
networks:
  python-network:
volumes:
  volume:
services:
  app:
    build: .
    links:
      - electrical
    depends_on:
      - electrical
    ports:
    - "5000:5000"
    networks:
      - python-network
    volumes: 
      - volume:/appblog
  electrical:
    image: mysql:latest
    networks:
      - python-network
    container_name: electrical
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: rootuser
      MYSQL_PASSWORD: rootpassword
      MYSQL_DATABASE: electrical
    networks:
      - python-network
    volumes: 
      - volume:/var/lib/mysql
